version: "3.8"
name: basic-bank-application-container

services:
  db:
    image: postgres
    container_name: pg-database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - database-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pg-admin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  database-data:
  pgadmin-data:
